// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportMermaid(arg1:string):Promise<string>;

export function ExportSQL(arg1:string,arg2:string):Promise<string>;

export function ImportMermaid(arg1:string):Promise<string>;

export function ImportSQL(arg1:string):Promise<string>;

export function Load(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Save(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
