// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportBigQuery(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportBigQuery'](arg1, arg2, arg3, arg4);
}

export function ExportMermaid(arg1) {
  return window['go']['app']['App']['ExportMermaid'](arg1);
}

export function ExportPlantUML(arg1) {
  return window['go']['app']['App']['ExportPlantUML'](arg1);
}

export function ExportPostgres(arg1, arg2) {
  return window['go']['app']['App']['ExportPostgres'](arg1, arg2);
}

export function ExportSQL(arg1, arg2) {
  return window['go']['app']['App']['ExportSQL'](arg1, arg2);
}

export function ImportMermaid(arg1) {
  return window['go']['app']['App']['ImportMermaid'](arg1);
}

export function ImportSQL(arg1) {
  return window['go']['app']['App']['ImportSQL'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['app']['App']['ListFiles'](arg1, arg2);
}

export function Load(arg1) {
  return window['go']['app']['App']['Load'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['app']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenFileDialog'](arg1, arg2, arg3);
}

export function Remove(arg1) {
  return window['go']['app']['App']['Remove'](arg1);
}

export function Save(arg1, arg2) {
  return window['go']['app']['App']['Save'](arg1, arg2);
}

export function SaveBase64(arg1, arg2) {
  return window['go']['app']['App']['SaveBase64'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveFileDialog'](arg1, arg2, arg3, arg4);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
