// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWorkspace(arg1:string):Promise<void>;

export function CreateWorkspace(arg1:string):Promise<string>;

export function DeleteCatalogField(arg1:string,arg2:string):Promise<void>;

export function DeleteCatalogRelationship(arg1:string,arg2:string):Promise<void>;

export function DeleteCatalogTable(arg1:string,arg2:string):Promise<void>;

export function DeleteConnectionProfile(arg1:string):Promise<void>;

export function DeleteDiagram(arg1:string,arg2:string):Promise<void>;

export function DeleteProfilePassword(arg1:string):Promise<void>;

export function DeleteWorkspaceConnectionProfile(arg1:string,arg2:string):Promise<void>;

export function ExportBigQuery(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ExportMermaid(arg1:string):Promise<string>;

export function ExportPlantUML(arg1:string):Promise<string>;

export function ExportPostgres(arg1:string,arg2:string):Promise<string>;

export function ExportSQL(arg1:string,arg2:string):Promise<string>;

export function GetCatalogRelationships(arg1:string):Promise<string>;

export function GetCatalogTables(arg1:string):Promise<string>;

export function GetDiagram(arg1:string,arg2:string):Promise<string>;

export function GetUIState(arg1:string):Promise<string>;

export function GetWorkspaceConnectionProfiles(arg1:string):Promise<string>;

export function GetWorkspaceSettings(arg1:string):Promise<string>;

export function ImportCSV(arg1:string,arg2:string):Promise<string>;

export function ImportFromDatabase(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ImportGlobalProfile(arg1:string,arg2:string):Promise<void>;

export function ImportMermaid(arg1:string):Promise<string>;

export function ImportSQL(arg1:string,arg2:string):Promise<string>;

export function ListConnectionProfiles():Promise<string>;

export function ListDatabaseSchemas(arg1:string):Promise<string>;

export function ListDatabaseTables(arg1:string,arg2:string):Promise<string>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function ListWorkspaceDiagrams(arg1:string):Promise<string>;

export function Load(arg1:string):Promise<string>;

export function LoadConnectionProfile(arg1:string):Promise<string>;

export function LoadOAuthClientConfig():Promise<string>;

export function LoadProfilePassword(arg1:string):Promise<string>;

export function MigrateWorkspace(arg1:string,arg2:string):Promise<string>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenWorkspace(arg1:string):Promise<string>;

export function Remove(arg1:string):Promise<void>;

export function Save(arg1:string,arg2:string):Promise<void>;

export function SaveBase64(arg1:string,arg2:string):Promise<void>;

export function SaveCatalogField(arg1:string,arg2:string):Promise<void>;

export function SaveCatalogRelationship(arg1:string,arg2:string):Promise<void>;

export function SaveCatalogTable(arg1:string,arg2:string):Promise<void>;

export function SaveConnectionProfile(arg1:string,arg2:string):Promise<void>;

export function SaveDiagram(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveOAuthClientConfig(arg1:string,arg2:string):Promise<void>;

export function SaveProfilePassword(arg1:string,arg2:string):Promise<void>;

export function SaveUIState(arg1:string,arg2:string):Promise<void>;

export function SaveWorkspaceConnectionProfile(arg1:string,arg2:string):Promise<void>;

export function SaveWorkspaceSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveWorkspaceSettings(arg1:string,arg2:string):Promise<void>;

export function TestDatabaseConnection(arg1:string):Promise<string>;

export function Version():Promise<string>;
