// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnectionProfile(arg1) {
  return window['go']['app']['App']['DeleteConnectionProfile'](arg1);
}

export function DeleteProfilePassword(arg1) {
  return window['go']['app']['App']['DeleteProfilePassword'](arg1);
}

export function ExportBigQuery(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportBigQuery'](arg1, arg2, arg3, arg4);
}

export function ExportMermaid(arg1) {
  return window['go']['app']['App']['ExportMermaid'](arg1);
}

export function ExportPlantUML(arg1) {
  return window['go']['app']['App']['ExportPlantUML'](arg1);
}

export function ExportPostgres(arg1, arg2) {
  return window['go']['app']['App']['ExportPostgres'](arg1, arg2);
}

export function ExportSQL(arg1, arg2) {
  return window['go']['app']['App']['ExportSQL'](arg1, arg2);
}

export function ImportCSV(arg1, arg2) {
  return window['go']['app']['App']['ImportCSV'](arg1, arg2);
}

export function ImportFromDatabase(arg1, arg2, arg3) {
  return window['go']['app']['App']['ImportFromDatabase'](arg1, arg2, arg3);
}

export function ImportMermaid(arg1) {
  return window['go']['app']['App']['ImportMermaid'](arg1);
}

export function ImportSQL(arg1, arg2) {
  return window['go']['app']['App']['ImportSQL'](arg1, arg2);
}

export function ListConnectionProfiles() {
  return window['go']['app']['App']['ListConnectionProfiles']();
}

export function ListDatabaseSchemas(arg1) {
  return window['go']['app']['App']['ListDatabaseSchemas'](arg1);
}

export function ListDatabaseTables(arg1, arg2) {
  return window['go']['app']['App']['ListDatabaseTables'](arg1, arg2);
}

export function ListFiles(arg1, arg2) {
  return window['go']['app']['App']['ListFiles'](arg1, arg2);
}

export function Load(arg1) {
  return window['go']['app']['App']['Load'](arg1);
}

export function LoadConnectionProfile(arg1) {
  return window['go']['app']['App']['LoadConnectionProfile'](arg1);
}

export function LoadOAuthClientConfig() {
  return window['go']['app']['App']['LoadOAuthClientConfig']();
}

export function LoadProfilePassword(arg1) {
  return window['go']['app']['App']['LoadProfilePassword'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['app']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenFileDialog'](arg1, arg2, arg3);
}

export function Remove(arg1) {
  return window['go']['app']['App']['Remove'](arg1);
}

export function Save(arg1, arg2) {
  return window['go']['app']['App']['Save'](arg1, arg2);
}

export function SaveBase64(arg1, arg2) {
  return window['go']['app']['App']['SaveBase64'](arg1, arg2);
}

export function SaveConnectionProfile(arg1, arg2) {
  return window['go']['app']['App']['SaveConnectionProfile'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveFileDialog'](arg1, arg2, arg3, arg4);
}

export function SaveOAuthClientConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveOAuthClientConfig'](arg1, arg2);
}

export function SaveProfilePassword(arg1, arg2) {
  return window['go']['app']['App']['SaveProfilePassword'](arg1, arg2);
}

export function TestDatabaseConnection(arg1) {
  return window['go']['app']['App']['TestDatabaseConnection'](arg1);
}

export function Version() {
  return window['go']['app']['App']['Version']();
}
