// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnectionProfile(arg1:string):Promise<void>;

export function DeleteProfilePassword(arg1:string):Promise<void>;

export function ExportBigQuery(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ExportMermaid(arg1:string):Promise<string>;

export function ExportPlantUML(arg1:string):Promise<string>;

export function ExportPostgres(arg1:string,arg2:string):Promise<string>;

export function ExportSQL(arg1:string,arg2:string):Promise<string>;

export function ImportCSV(arg1:string,arg2:string):Promise<string>;

export function ImportFromDatabase(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ImportMermaid(arg1:string):Promise<string>;

export function ImportSQL(arg1:string,arg2:string):Promise<string>;

export function ListConnectionProfiles():Promise<string>;

export function ListDatabaseSchemas(arg1:string):Promise<string>;

export function ListDatabaseTables(arg1:string,arg2:string):Promise<string>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function Load(arg1:string):Promise<string>;

export function LoadConnectionProfile(arg1:string):Promise<string>;

export function LoadOAuthClientConfig():Promise<string>;

export function LoadProfilePassword(arg1:string):Promise<string>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Remove(arg1:string):Promise<void>;

export function Save(arg1:string,arg2:string):Promise<void>;

export function SaveBase64(arg1:string,arg2:string):Promise<void>;

export function SaveConnectionProfile(arg1:string,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveOAuthClientConfig(arg1:string,arg2:string):Promise<void>;

export function SaveProfilePassword(arg1:string,arg2:string):Promise<void>;

export function TestDatabaseConnection(arg1:string):Promise<string>;

export function Version():Promise<string>;
