// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportMermaid(arg1) {
  return window['go']['app']['App']['ExportMermaid'](arg1);
}

export function ExportSQL(arg1, arg2) {
  return window['go']['app']['App']['ExportSQL'](arg1, arg2);
}

export function ImportMermaid(arg1) {
  return window['go']['app']['App']['ImportMermaid'](arg1);
}

export function ImportSQL(arg1) {
  return window['go']['app']['App']['ImportSQL'](arg1);
}

export function Load(arg1) {
  return window['go']['app']['App']['Load'](arg1);
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['app']['App']['OpenFileDialog'](arg1, arg2, arg3);
}

export function Save(arg1, arg2) {
  return window['go']['app']['App']['Save'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveFileDialog'](arg1, arg2, arg3, arg4);
}
